### PR TITLE
fix: use type `Session` from `next-auth`

### LINKED ISSUE #112: Streamline typing across next auth session data and `useSession` data type
### Describe the feature

Raised by @noook in [#61:](https://github.com/sidebase/nuxt-auth/issues/61#issuecomment-1356826150)

> The signature for `useSession` does not go alone this answer :(

image

> `useSession().data` does not refer to next-auth types so overriding it does not help much when using the type outside of the NuxtAuth handler

We should:
- [ ] ensure that both have the same data-type, so that it can be overwritten easily.
- [ ] update the recipe on how to add custom session data https://sidebase.io/nuxt-auth/recipes/custom-session-data
  - source is here: https://github.com/sidebase/nuxt-auth/blob/main/docs/content/5.recipes/4.custom-session-data.md

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JoaoPedroAS51**
Add types `UseSessionReturn` and `UseSessionStateReturn`

Closes #112 

Checklist:
- [x] manually checked my feature / checking not applicable
- [ ] wrote tests / testing not applicable
- [ ] attached screenshots / screenshot not applicable

### CODE REVIEW

File: src/runtime/composables/useSession.ts [hunk 1]
```diff
@@ -69,7 +75,8 @@ const getCsrfToken = () => {
 }
 
 /**
- * Trigger a sign in flow for the passed `provider`. If no provider is given the sign in page for all providers will be shown.
+ * Trigger a sign in flow for the passed `provider`. If no provider is given the sign in page for all providers will be
+ * shown.
```
Comment (BracketJohn) [inline src/runtime/composables/useSession.ts:79]: nit: was this moved to a newline on accident? :D

**Review by BracketJohn — COMMENTED** [review]
So after this PR types will correctly reference what we setup in our own module, but will the approach to overwrite them by overwriting the `next-auth` types outlined here work afterwards: https://sidebase.io/nuxt-auth/recipes/custom-session-data? 🤔

File: src/runtime/composables/useSession.ts (hunk 1 above)
Comment (JoaoPedroAS51) [reply src/runtime/composables/useSession.ts:79]: > So after this PR types will correctly reference what we setup in our own module, but will the approach to overwrite them by overwriting the `next-auth` types outlined here work afterwards: https://sidebase.io/nuxt-auth/recipes/custom-session-data? 🤔

Yes, it will work by overwriting the `next-auth` types. 

A little bit of context: My guess is that nuxt auto-imports was generating the result of `Session` type instead of referencing it. So I fixed it to use the `Session` from `next-auth`.

**Review by BracketJohn — APPROVED** [review]

**Comment by BracketJohn** [comment]
Thanks for the explanation (: Change seems good, I also checked it locally now (:
