### PR TITLE
fix: do not use async composables in auth middleware

### LINKED ISSUE #132: `Error: nuxt instance unavailable` when signing out from a protected page
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `css`, `modules`, `auth`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.0`, `@sidebase/nuxt-auth@0.3.2`

### Reproduction

https://github.com/LLCampos/nuxt-auth-example

This [commit](https://github.com/LLCampos/nuxt-auth-example/commit/fd1d0118e07127e3a7fd51c1269cc6eb08e6e70a) contains the changes necessary to the current example app to reproduce the issue.

### Describe the bug

* Start application
* It should immediately take you to login page
* Login with credentials
* Logout

I get the following in logs

```
[Vue Router warn]: uncaught error during route navigation:                                                                                                            11:09:23
Error: nuxt instance unavailable                                                                                                                                      11:09:23
    at useNuxtApp (/Users/luiscampos/Development/nuxt-auth-example/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useRuntimeConfig (/Users/luiscampos/Development/nuxt-auth-example/node_modules/nuxt/dist/app/nuxt.mjs:173:10)
    at getApiURL (/Users/luiscampos/Development/nuxt-auth-example/node_modules/@sidebase/nuxt-auth/dist/runtime/utils/url.mjs:10:40)
    at Module.joinPathToApiURL (/Users/luiscampos/Development/nuxt-auth-example/node_modules/@sidebase/nuxt-auth/dist/runtime/utils/url.mjs:15:66)
    at /Users/luiscampos/Development/nuxt-auth-example/node_modules/@sidebase/nuxt-auth/dist/runtime/middleware/auth.mjs:16:65
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.callAsync (file:///Users/luiscampos/Development/nuxt-auth-example/node_modules/unctx/dist/index.mjs:53:16)
    at async /Users/luiscampos/Development/nuxt-auth-example/node_modules/nuxt/dist/pages/runtime/router.mjs:110:22
[Vue Router warn]: uncaught error during route navigation:                                                                                                            11:09:23
Error: nuxt instance unavailable                                                                                                                                      11:09:23
    at useNuxtApp (/Users/luiscampos/Development/nuxt-auth-example/node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useRuntimeConfig (/Users/luiscampos/Development/nuxt-auth-example/node_modules/nuxt/dist/app/nuxt.mjs:173:10)
    at getApiURL (/Users/luiscampos/Development/nuxt-auth-example/node_modules/@sidebase/nuxt-auth/dist/runtime/utils/url.mjs:10:40)
    at Module.joinPathToApiURL (/Users/luiscampos/Development/nuxt-auth-example/node_modules/@sidebase/nuxt-auth/dist/runtime/utils/url.mjs:15:66)
    at /Users/luiscampos/Development/nuxt-auth-example/node_modules/@sidebase/nuxt-auth/dist/runtime/middleware/auth.mjs:16:65
    at async Object.callAsync (file:///Users/luiscampos/Development/nuxt-auth-example/node_modules/unctx/dist/index.mjs:53:16)
    at async /Users/luiscampos/Development/nuxt-auth-example/node_modules/nuxt/dist/pages/runtime/router.mjs:110:22
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client                                                11:09:23
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at setResponseHeader (file:///Users/luiscampos/Development/nuxt-auth-example/node_modules/nitropack/node_modules/h3/dist/index.mjs:277:18)
    at Object.errorhandler [as onError] (file:///Users/luiscampos/Development/nuxt-auth-example/.nuxt/dev/index.mjs:450:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.toNodeHandle (file:///Users/luiscampos/Development/nuxt-auth-example/node_modules/nitropack/node_modules/h3/dist/index.mjs:752:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
```

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by BracketJohn**
Closes #132

This PR:
- manually assembles a navigate to call, taking into account:
  - the original target of the request for `callback`
  - setting the correct `error` code for the sign-in page that is redirected to
- adds early 404 redirects to not enforce authentication for 404 pages per default
- adds a configuration option to change the aforementioned 404-behavior

This fully resolves the `ERR_HTTP_HEADERS_SENT` problem 🎊 It seems to be related to redirecting to a 404-page and may be the same as https://github.com/nuxt/framework/issues/9438. The problem will still occur when enforcing authentication for 404 pages by setting `allow404WithoutAuth: false`.

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] manually checked my feature / checking not applicable
- [x] wrote tests / testing not applicable
- [x] attached screenshots / screenshot not applicable

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -75,7 +94,10 @@ const defaults: ModuleOptions & { basePath: string } = {
   trustHost: false,
   enableSessionRefreshPeriodically: false,
   enableSessionRefreshOnWindowFocus: true,
-  enableGlobalAppMiddleware: false
+  enableGlobalAppMiddleware: false,
```
Comment (JoaoPedroAS51) [inline src/module.ts:97]: Maybe we can merge `enableGlobalAppMiddleware` with `globalMiddlewareOptions`, so we have all in one place. What do you think?

Something like this:
```ts
globalAppMiddleware: {
  enabled: false,
  allow404WithoutAuth: true
}
```

File: src/runtime/middleware/auth.ts [hunk 2]
```diff
@@ -1,32 +1,68 @@
...
+  // adapted from: https://github.com/nuxt/framework/blob/ab2456c295fc8c7609a7ef7ca1e47def5d087e87/packages/nuxt/src/app/composables/router.ts#L97-L115
+  if (process.server) {
+    const nuxtApp = useNuxtApp()
+    if (nuxtApp.ssrContext && nuxtApp.ssrContext.event) {
+      return nuxtApp.callHook('app:redirected').then(() => sendRedirect(nuxtApp.ssrContext!.event, url, 302))
+    }
+  }
+
+  window.location.href = url
+  return navigateTo(undefined)
```
Comment (JoaoPedroAS51) [inline src/runtime/middleware/auth.ts:67]: In my tests I noticed that `navigateTo(undefined)` will redirect the user to `/` before redirecting to signIn, in client side. `navigateTo` defaults to `/` when the path is not provided. See https://github.com/nuxt/framework/blob/ab2456c295fc8c7609a7ef7ca1e47def5d087e87/packages/nuxt/src/app/composables/router.ts#L77-L79

To reproduce: go to [page that is always unprotected](http://localhost:3000/always-unprotected), then click  [globally protected page](http://localhost:3000/protected/globally). You will see a content-flash of the home page, and if you go back it will go to home page.

I'm not sure how to solve this :/

**Review by JoaoPedroAS51 — CHANGES_REQUESTED** [review]
Nice work! And good catch about the 404 page!

Just found one issue in client side redirect, I added a comment there

File: src/module.ts (hunk 1 above)
Comment (BracketJohn) [reply src/module.ts:97]: I like the idea very much, I think it could even have a signature of:
```
globalAppMiddleware: boolean | GlobalAppMiddlewareOptions
```

with `false` turning it off, `true` turning it on with default config and `{ ... }` allowing for granular configuration. 

An issue with this approach and why I didn't go with it so far:
- breaks backwards-compat (less severe if we go with the `boolean | ...` signature)
- maybe does not work with the way that `nuxt/schema` generates the typings for the config keys -> there's some really weird errors there

I would look into whether I can mitigate the two problems and add it here, otherwise I propose that we move it to the future, maybe also as part of a `0.4.x` jump in versioning (incoming anyways, due to requirement to make `next-auth ` a peer-dep which is definitely a breaking change, see #128 for example)

Comment (JoaoPedroAS51) [reply src/module.ts:97]: I liked the signature you suggested! Agreed.

One thing about versioning, maybe we should warn users to fix the exact version they are using to avoid breaking changes until we release v1.0.0

File: src/runtime/middleware/auth.ts (hunk 2 above)
Comment (BracketJohn) [reply src/runtime/middleware/auth.ts]: Looked into it -> figured out that there is a bit less magic than I though: As long as we return a `Promise` that does not resolve immeadiatly, the content of the protected page will not be loaded.

I now set it to 100ms: It should never actually be awaited but will block the navigation for up to `100ms` or until the navigation to the singin-page completes (which should always be faster than 100ms, I hope?).

- Does this resolve the issue?
- Do you think 100ms is enough or should we increase it?

Comment (JoaoPedroAS51) [reply src/runtime/middleware/auth.ts]: Yeah, this actually works!!! But I think 100ms is not enough for slow connections. If I set network to slow 3g in the browser, I can see the content-flash for a long time.

If we set the `setTimeout` to `Infinity`, it solves completely. Can we possible cause a side-effect by using `Infinity` here? I have not used it before haha

Comment (BracketJohn) [reply src/runtime/middleware/auth.ts]: Woop wooop 🎊 

Good catch - I wanted to avoid using `Infinity`, so as a (good I think?) compromise I adapted the behavior:
- wait for up to 60 seconds
- if that does not work: delegate control back to `vue-router` -> this will still avoid content-flashes. The only downside is that it will log a `404` error in the console because vue-router does not know about the signin page

File: src/module.ts (hunk 1 above)
Comment (BracketJohn) [reply src/module.ts:97]: We're already following the policy of only releasing:
- patch changes that are non-breaking.
- minor changes if something breaking happened 

Do you think that's enough to avoid what you described?

File: src/runtime/middleware/auth.ts (hunk 2 above)
Comment (JoaoPedroAS51) [reply src/runtime/middleware/auth.ts]: Yeah, I think this is good. Tested here and seems to work fine!

**Review by JoaoPedroAS51 — APPROVED** [review]

File: src/module.ts (hunk 1 above)
Comment (JoaoPedroAS51) [reply src/module.ts:97]: Yeah, based on what you said on discord about the approach of using `0.x` for now, I guess so.
But I think we could suggest users to add `nuxt-auth` using `~0.x` instead of `^0.x` in `package.json`, so it will only update to future patch versions, without incrementing the minor version.
