### PR TITLE
enh(#742): optimize internal $fetch calls

### LINKED ISSUE #742: perf: server side fetch requests made to various endpoints
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.7.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/warflash/nuxt-auth-debug

Using the module's `playground-authjs` dir.

### Describe the bug

In our production env we noticed a ton of `/api/auth/session?callbackUrl=http:%2F%2Flocalhost:3333%2Falways-unprotected` requests coming through our proxy layer, all with user agent set to "node".

To debug this I spun up a local version of the playground of the repo and attached a proxy, -> see repro above.

I am not logged in on the local playground, depite that:

In the logs below you can see me calling for `/always-unprotected` with my browsers user agent in the first line.
Then 3 requests are fired for  `/api/auth/session?callbackUrl=http:%2F%2Flocalhost:3333%2Falways-unprotected` (which is what we've been seeing in our prod proxy logs as well, followed by `/api/auth/providers` and `/api/auth/csrf`.

### Additional context

Wanted to perhaps spark a discussion or question on whether these calls can be avoided or made internally using $fetch or at least limited to users that are actually logged in or pages that are protected. Sending out a full http request for all of these adds a considerable amount of overhead and delay to the rendered SSR page.

### Logs

```shell-script
Received request for /always-unprotected
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /api/auth/session?callbackUrl=http:%2F%2Flocalhost:3333%2Falways-unprotected
"node"
Received request for /api/auth/providers
"node"
Received request for /api/auth/csrf
"node"
Received request for /_nuxt/DdW6MrNW.js
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /_nuxt/CiQvDwpd.js
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /_nuxt/DZ4PCLmw.js
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /_nuxt/ChRk-71c.js
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /_nuxt/DlAUqK2U.js
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /_nuxt/CuxXRkfr.js
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /_nuxt/builds/meta/28820aa0-4610-4b7e-b225-6a545c117d71.json
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /favicon.ico
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /api/auth/providers
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /api/auth/csrf
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Received request for /api/token
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
```

### PR DESCRIPTION
**Pull request by phoenix-ru**
### 🔗 Linked issue

Closes #742 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
This fixes `_fetch` usage, getting rid of internal HTTP calls being made to itself and properly using `$fetch`

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by phoenix-ru** [comment]
Ping to @warflash

File: src/runtime/utils/url.ts [hunk 1]
```diff
@@ -5,7 +5,17 @@ import type { ModuleOptionsNormalized } from '../types'
...
 export const getRequestURL = (includePath = true) => getURL(useRequestEvent()?.node.req, includePath)
-export const joinPathToApiURL = (path: string) => joinURL(useAuthState()._internal.baseURL, path)
+export function joinPathToApiURL (path: string) {
+  const authStateInternal = useAuthState()._internal
+
+  // For internal calls, use a different base
+  // https://github.com/sidebase/nuxt-auth/issues/742
+  const base = path.startsWith('/')
+    ? authStateInternal.pathname
+    : authStateInternal.baseURL
```
Comment (BracketJohn) [inline src/runtime/utils/url.ts:15]: One thing I worry about: Relying on `/` to determine whether a path is internal -> is there another way? I think there may be / should be, as we know which endpoints we are registering

Comment (phoenix-ru) [reply src/runtime/utils/url.ts:15]: This is exactly what $fetch does under the hood — it looks at the first character in the passed string and if it is `/`, does an internal dispatch.

I don't know of a way to check internal API routes otherwise, so suggestions would be welcome

Comment (BracketJohn) [reply src/runtime/utils/url.ts:15]: Ah I see - in that case, let's do it like this then (:

**Review by BracketJohn — APPROVED** [review]

**Review by zoey-kaiser — APPROVED** [review]
